language: perl

perl:

jobs:
  include:
    - perl: "5.30"
      env: COVERAGE=1
    - perl: "5.14"
      env: RELEASE_TESTING=1
    - perl: "5.8"

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
