language: perl

perl:
  - "5.32"
  - "5.26"
  - "5.14"
  - "5.8"
  - "blead"

matrix:
  allow_failures:
    - perl: blead

env:
  global:
    - RELEASE_TESTING=1

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
